SELECT MAX(MONTHS*SALARY), COUNT(MONTHS*SALARY) FROM EMPLOYEE WHERE MONTHS*SALARY  IN (SELECT MAX(MONTHS*SALARY) FROM EMPLOYEE)

/*
SELECT MAX(MONTHS*SALARY), COUNT(MONTHS*SALARY) FROM EMPLOYEE WHERE MONTHS*SALARY = (SELECT MAX(MONTHS*SALARY) FROM EMPLOYEE)

SELECT MONTHS*SALARY AS EARNINGS , COUNT(*) FROM EMPLOYEE GROUP BY 1 ORDER BY 1 DESC LIMIT 1

*/
