SELECT ROUND(LAT_N,4) 
FROM STATION S
WHERE (SELECT COUNT(LAT_N) FROM STATION WHERE LAT_N < S.LAT_N) = (SELECT COUNT(LAT_N) FROM STATION WHERE LAT_N > S.LAT_N)

/*

SELECT ROUND(LAT_N,4) 
FROM STATION S
WHERE (SELECT CEIL(COUNT(ID)/2)-1 FROM STATION) = (SELECT COUNT(LAT_N) FROM STATION S1 WHERE S1.LAT_N<S.LAT_N) // HERE WE ADD -1 because we have to remove the median value



*/
